spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rc_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: NewStrongPass!
  jooq:
    sql-dialect: MYSQL

notification:
  dispatcher:
    interval-ms: 2000
